import os

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    'Home': 'Hjem',
    'About Us': 'Om oss',
    'Contact Us': 'Kontakt oss',
    'Shop Online': 'Handle på nett',
    'Contact Info': 'Kontaktinformasjon',
    'Follow Us': 'Følg oss',
    'APNI MARKET — FOOD\n                           &\n                           BUSINESS ESSENTIALS': 'APNI MARKET — MAT\n                           &\n                           NÆRINGSMIDLER',
    'APNI MARKET — FOOD & BUSINESS ESSENTIALS': 'APNI MARKET — MAT & NÆRINGSMIDLER',
    'Stock Your Kitchen.\n                           Keep Business Moving.': 'Fyll opp kjøkkenet.\n                           Hold bedriften i gang.',
    'Shop food, drinks, packaging, and everyday supplies for your restaurant,<br> takeaway, or commercial kitchen—all in one place.': 'Kjøp mat, drikke, emballasje og dagligvarer til din restaurant,<br> takeaway eller storkjøkken—alt på ett sted.',
    'Shop Now': 'Kjøp nå',
    'Explore Products': 'Utforsk produkter',
    'FROM PREPARATION TO TAKEAWAY': 'FRA FORBEREDELSE TIL TAKEAWAY',
    'FROM PREPARATION TO\n                           TAKEAWAY': 'FRA FORBEREDELSE TIL\n                           TAKEAWAY',
    'Great Food Starts With the Right Supplies.': 'God mat starter med de riktige råvarene.',
    'Great Food Starts With\n                           the Right Supplies.': 'God mat starter med\n                           de riktige råvarene.',
    'From kitchen ingredients to takeaway packaging, find the essentials<br>\n                           you need to prepare, serve, and send out every order.': 'Fra ingredienser til takeaway-emballasje, finn det du trenger<br>\n                           for å forberede, servere og sende ut hver bestilling.',
    'From kitchen ingredients to takeaway packaging, find the essentials<br> you need to prepare, serve, and send out every order.': 'Fra ingredienser til takeaway-emballasje, finn det du trenger<br> for å forberede, servere og sende ut hver bestilling.',
    'Browse Products': 'Se produkter',
    'View Offers': 'Se tilbud',
    'MAKE YOUR NEXT STOCK-UP COUNT': 'GJØR DITT NESTE INNKJØP LØNNSOMT',
    'MAKE YOUR NEXT\n                           STOCK-UP COUNT': 'GJØR DITT NESTE\n                           INNKJØP LØNNSOMT',
    'Everyday Essentials.\n                           More Value for Your Business.': 'Hverdagslige nødvendigheter.\n                           Mer verdi for din bedrift.',
    'Explore current offers and discover products for your next order.<br>\n                           Keep your shelves stocked and your menu ready.': 'Utforsk aktuelle tilbud og oppdag produkter for din neste bestilling.<br>\n                           Hold hyllene fylt og menyen klar.',
    'Explore current offers and discover products for your next order.<br> Keep your shelves stocked and your menu ready.': 'Utforsk aktuelle tilbud og oppdag produkter for din neste bestilling.<br> Hold hyllene fylt og menyen klar.',
    'Shop All Products': 'Kjøp alle produkter',
    'Food and products for preparation': 'Mat og produkter for tilberedning',
    'Packaging and service essentials': 'Emballasje og serveringsutstyr',
    'Drinks and chilled goods': 'Drikke og kjølevarer',
    'Convenient online shopping': 'Praktisk netthandel',
    'ABOUT APNI MARKET': 'OM APNI MARKET',
    'Your Kitchen Has a Lot to Do.\n                           <br> Make Shopping Simpler.': 'Kjøkkenet ditt har mye å gjøre.\n                           <br> Gjør innkjøpene enklere.',
    'Your Kitchen Has a Lot to Do. <br> Make Shopping Simpler.': 'Kjøkkenet ditt har mye å gjøre. <br> Gjør innkjøpene enklere.',
    'A busy kitchen needs more than ingredients. It needs packaging for the next<br> takeaway, drinks for the fridge, and supplies for the work behind the scenes.<br>\n                           Apni Market brings these essentials together, helping you organise your purchasing around the\n                           way your business works.': 'Et travelt kjøkken trenger mer enn ingredienser. Det trenger emballasje til neste<br> takeaway, drikke i kjøleskapet og utstyr til arbeidet bak kulissene.<br>\n                           Apni Market samler disse nødvendighetene, og hjelper deg å organisere innkjøpene etter\n                           hvordan bedriften din fungerer.',
    'A busy kitchen needs more than ingredients. It needs packaging for the next<br> takeaway, drinks for the fridge, and supplies for the work behind the scenes.<br> Apni Market brings these essentials together, helping you organise your purchasing around the way your business works.': 'Et travelt kjøkken trenger mer enn ingredienser. Det trenger emballasje til neste<br> takeaway, drikke i kjøleskapet og utstyr til arbeidet bak kulissene.<br> Apni Market samler disse nødvendighetene, og hjelper deg å organisere innkjøpene etter hvordan bedriften din fungerer.',
    'Food and everyday business supplies': 'Mat og daglige forsyninger',
    'Chilled, frozen, and dry goods': 'Kjølevarer, frossenmat og tørrvarer',
    'Products for preparation and service': 'Produkter for tilberedning og servering',
    'Looking for Something Specific?': 'Leter du etter noe spesielt?',
    'Tell us what you need. If you cannot find a product in our store, we\\'ll do our best to source it for you.': 'Fortell oss hva du trenger. Finner du ikke et produkt i butikken vår, vil vi gjøre vårt beste for å skaffe det for deg.',
    'Contact Our Team': 'Kontakt vårt team',
    'WHO WE SERVE': 'HVEM VI LEVERER TIL',
    'Your Business. Our Everyday Essentials.': 'Din bedrift. Våre hverdagslige nødvendigheter.',
    'Your Business. Our Everyday\n                  Essentials.': 'Din bedrift. Våre hverdagslige\n                  nødvendigheter.',
    'From restaurants and fast-food outlets to hotels and canteens, Apni Market brings together food, drinks, packaging, and everyday supplies to keep your business running.': 'Fra restauranter og gatekjøkken til hoteller og kantiner; Apni Market samler mat, drikke, emballasje og dagligvarer for å holde bedriften din i gang.',
    'Restaurants': 'Restauranter',
    'From kitchen preparation to the final plate, find ingredients, drinks, and everyday essentials for your restaurant. Bring your purchasing together so your team can focus on preparing great food and looking after guests.': 'Fra forberedelse på kjøkkenet til den ferdige tallerkenen, finn ingredienser, drikke og daglige nødvendigheter til restauranten din. Samle innkjøpene dine slik at teamet kan fokusere på å lage god mat og ta vare på gjestene.',
    'Fast-Food Businesses': 'Gatekjøkken og hurtigmat',
    'Keep your kitchen ready for the next order with ingredients, sauces, drinks, and takeaway packaging. Find the everyday supplies you need to prepare, pack, and serve throughout a busy service.': 'Hold kjøkkenet klart for neste bestilling med ingredienser, sauser, drikke og takeaway-emballasje. Finn utstyret du trenger for å forberede, pakke og servere gjennom en travel arbeidsdag.',
    'Hotels': 'Hoteller',
    'Support breakfast service, restaurant dining, and daily hospitality needs with food, beverages, and practical supplies. Bring essentials together in one place to simplify purchasing for your team.': 'Støtt frokostservering, restaurantmiddager og daglige gjestebehov med mat, drikke og praktiske forsyninger. Samle alt på ett sted for å forenkle innkjøp for teamet ditt.',
    'Canteens': 'Kantiner',
    'Prepare for daily meal service with cooking ingredients, drinks, and serving essentials. Stock your workplace or institutional kitchen with supplies that help your team plan, prepare, and serve meals efficiently.': 'Forbered deg på daglig måltidsservering med ingredienser, drikke og serveringsutstyr. Fyll opp din kantine eller storkjøkken med utstyr som hjelper teamet å planlegge, forberede og servere måltider effektivt.',
    'SHOP FOR YOUR MENU': 'HANDEL TIL DIN MENY',
    'What\\'s on Your Next Order?': 'Hva står på din neste bestilling?',
    'Start with the products that suit your menu and build your basket<br>around your kitchen\\'s needs.': 'Start med produktene som passer til menyen din og bygg opp handlekurven<br>rundt kjøkkenets behov.',
    'Dry Goods &amp; Bakery': 'Tørrvarer &amp; bakeri',
    'Dry goods, bakery products': 'Tørrvarer, bakervarer',
    'Chilled, Frozen &amp; Dairy': 'Kjølt, fryst &amp; meieri',
    'Chilled foods, frozen foods, dairy products': 'Kjølevarer, frossenmat, meieriprodukter',
    'Drinks &amp; Beverages': 'Drikke &amp; drikkevarer',
    'All drinks and beverages': 'All drikke og drikkevarer',
    'Packaging &amp; Hygiene': 'Emballasje &amp; hygiene',
    'Food packaging, cleaning and hygiene supplies': 'Matemballasje, rengjøring og hygieneartikler',
    'Equipment &amp; Office Supplies': 'Utstyr &amp; kontorrekvisita',
    'Kitchen equipment, office supplies': 'Kjøkkenutstyr, kontorrekvisita',
    'SIMPLE ONLINE SHOPPING': 'ENKEL NETHANDEL',
    'Your Next Stock-Up Starts Here.': 'Din neste oppfylling starter her.',
    'Find your essentials and put together an order that works<br>\n                  for your business.': 'Finn det du trenger og sett sammen en bestilling som fungerer<br>\n                  for din bedrift.',
    '01 — Browse\n                              the Range': '01 — Bla gjennom\n                              utvalget',
    'Explore categories or search for<br>a specific product.': 'Utforsk kategorier eller søk etter<br>et spesifikt produkt.',
    '02 — Choose\n                              Your Products': '02 — Velg\n                              dine produkter',
    'Check pack sizes and product<br>details, then select your quantities.': 'Sjekk pakkestørrelser og produkt-<br>detaljer, velg deretter antall.',
    '03 — Review\n                              Your Basket': '03 — Se over\n                              handlekurven',
    'Check your items and make any<br>final changes before checkout.': 'Kontroller varene dine og gjør<br>siste endringer før kassen.',
    '04 — Place\n                              Your Order': '04 — Fullfør\n                              bestilling',
    'Follow the checkout steps to<br>complete your purchase.': 'Følg stegene i kassen for å<br>fullføre kjøpet ditt.',
    'LET\\'S TALK ABOUT YOUR NEXT ORDER': 'LA OSS SNAKKE OM DIN NESTE BESTILLING',
    'Can\\'t Find What You Need?': 'Finner du ikke det du trenger?',
    'Looking for a particular ingredient, pack size, or business supply?<br>Send us the details so we can look into it.': 'Leter du etter en bestemt ingrediens, pakkestørrelse eller utstyr?<br>Send oss detaljene så vi kan se på det.',
    'Product Enquiries': 'Produkthenvendelser',
    'Ask about an item before adding it<br> to your order. We\\'re happy to help<br> with any product questions you<br> might have.': 'Spør om en vare før du legger den<br> til i bestillingen. Vi hjelper deg gjerne<br> med spørsmål om produkter du<br> måtte ha.',
    'Get in Touch': 'Ta kontakt',
    'Sourcing Requests': 'Forespørsler om innkjøp',
    'Tell us about a product you would<br> like us to source. We will do our<br> best to find it and add it<br> to our range.': 'Fortell oss om et produkt du vil<br> at vi skal skaffe. Vi vil gjøre vårt<br> beste for å finne det og legge det til<br> i sortimentet vårt.',
    'Order Questions': 'Spørsmål om bestilling',
    'Get in touch with a question about<br> your purchase. We are here to<br> help resolve any issues<br> quickly.': 'Ta kontakt med spørsmål om<br> kjøpet ditt. Vi er her for å<br> hjelpe deg med å løse eventuelle problemer<br> raskt.',
    'Read about how our tailored solutions have helped businesses achieve.': 'Les om hvordan våre skreddersydde løsninger har hjulpet bedrifter med å lykkes.',
    'Read about how our tailored solutions have helped businesses\n                     achieve.': 'Les om hvordan våre skreddersydde løsninger har hjulpet bedrifter\n                     med å lykkes.',
    'Our clients\\' satisfaction is our top priority,<br> and their feedback speaks volumes about our dedication to excellence. We take immense <br> pride in the positive experiences shared by businesses across various industries who rely <br> on our transport and logistics expertise.': 'Våre kunders tilfredshet er vår høyeste prioritet,<br> og deres tilbakemeldinger sier mye om vår dedikasjon til fortreffelighet. Vi er enormt <br> stolte over de positive opplevelsene som deles av bedrifter på tvers av ulike bransjer som stoler <br> på vår ekspertise.',
    'CONTACT APNI MARKET': 'KONTAKT APNI MARKET',
    'Tell Us What Your Business Needs.': 'Fortell oss hva bedriften din trenger.',
    'Have a product question or planning your next order?<br> Send us a message.': 'Har du et produktspørsmål eller planlegger din neste bestilling?<br> Send oss en melding.',
    'Send an Enquiry': 'Send en henvendelse',
    'Have a product question or planning your next order? Send us a message and we will get back to you.': 'Har du et produktspørsmål eller planlegger din neste bestilling? Send oss en melding så kommer vi tilbake til deg.',
    'First Name': 'Fornavn',
    'Last Name': 'Etternavn',
    'Phone Number': 'Telefonnummer',
    'Email Address': 'E-postadresse',
    'Enquiry Type': 'Henvendelsestype',
    'Select Enquiry Type': 'Velg henvendelsestype',
    'Product Question': 'Produktspørsmål',
    'Product Sourcing': 'Skaffe produkt',
    'Delivery Enquiry': 'Spørsmål om levering',
    'Existing Order': 'Eksisterende bestilling',
    'Other': 'Annet',
    'Your Message': 'Din melding',
    'Send Message': 'Send melding',
    'Visit Us': 'Besøk oss',
    'Call Us': 'Ring oss',
    'Email Us': 'Send oss e-post',
    'Our Blog': 'Vår blogg',
    'Best Practices and Strategies': 'Beste praksis og strategier',
    'Gain insights into effective warehouse management strategies that<br> maximize space, improve accuracy, and boost productivity.': 'Få innsikt i effektive strategier for lagerstyring som<br> maksimerer plassen, forbedrer nøyaktigheten og øker produktiviteten.',
    'March 21, 2024': '21. mars 2024',
    'March 20, 2024': '20. mars 2024',
    'March 18, 2024': '18. mars 2024',
    'Transport & Logistics': 'Transport & Logistikk',
    'Optimizing Last-Mile Delivery: Strategies for Success': 'Optimalisering av Last-Mile levering: Strategier for suksess',
    'Delve into the challenges of last-mile delivery <br>and explore strategies to overcome them.': 'Dykk ned i utfordringene med last-mile levering <br>og utforsk strategier for å overvinne dem.',
    'Read More': 'Les mer',
    'Handling Project Cargo: Expert<br> Tips and Strategies': 'Håndtering av prosjektlast: Ekspert<br>tips og strategier',
    'Get expert tips on managing project cargo <br> logistics. From planning and coordination.': 'Få eksperttips om styring av prosjektlast-<br>logistikk. Fra planlegging og koordinering.',
    'The Importance of Reliable Freight Forwarding Services': 'Viktigheten av pålitelige speditørtjenester',
    'Learn practical strategies for optimizing your<br> supply chain operations, improve delivery.': 'Lær praktiske strategier for å optimalisere dine<br> forsyningskjedeoperasjoner, forbedre levering.',
    'Join Us Today And let Us Help You To Grow Your Business.': 'Bli med oss i dag, og la oss hjelpe deg med å utvide bedriften din.',
    'Get Started': 'Kom i gang',
    'Our global reach, combined with local <br> expertise, ensures that your goods are <br>transported safely, on time.': 'Vår globale rekkevidde, kombinert med lokal <br> ekspertise, sikrer at varene dine <br>transporteres trygt og til rett tid.',
    'Contact Information': 'Kontaktinformasjon',
    'Terms & Conditions': 'Vilkår og betingelser',
    'Privacy Policy': 'Personvernerklæring'
}

for old, new in replacements.items():
    content = content.replace(old, new)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(content)

print('Translation complete')
